### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by AxelDolislager** [devfacet/weather#10]
Is it possible to add and set languages to this?

**Comment by nicogon** [comment]
It has lang support

 weather.find({ search: 'Buenos aires', degreeType: 'C', **lang: 'ES'** }, function(err, result) { ....

**Comment by josuebasurto** [comment]
Not working as @nicogon said... 
```

{ Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/Users/jbasurto/Documents/NodeMinis/SlackWeather/node_modules/request/request.js:816:19)
    at Object.onceWrapper (events.js:285:13)
    at ClientRequest.emit (events.js:197:13)
    at Socket.emitRequestTimeout (_http_client.js:668:40)
    at Object.onceWrapper (events.js:285:13)
    at Socket.emit (events.js:197:13)
    at Socket._onTimeout (net.js:447:8)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5) code: 'ESOCKETTIMEDOUT', connect: false }
/Users/jbasurto/Documents/NodeMinis/SlackWeather/index.js:10
  var place = result[0];
                    ^

TypeError: Cannot read property '0' of undefined
    at /Users/jbasurto/Documents/NodeMinis/SlackWeather/index.js:10:21
    at Request._callback (/Users/jbasurto/Documents/NodeMinis/SlackWeather/node_modules/weather-js/index.js:42:41)
    at self.callback (/Users/jbasurto/Documents/NodeMinis/SlackWeather/node_modules/request/request.js:185:22)
    at Request.emit (events.js:197:13)
    at ClientRequest.<anonymous> (/Users/jbasurto/Documents/NodeMinis/SlackWeather/node_modules/request/request.js:819:16)
    at Object.onceWrapper (events.js:285:13)
    at ClientRequest.emit (events.js:197:13)
    at Socket.emitRequestTimeout (_http_client.js:668:40)
    at Object.onceWrapper (events.js:285:13)
    at Socket.emit (events.js:197:13)

```

**Comment by josuebasurto** [comment]
The 'lang' parameter translates to culture parameter in Microsoft so I discovered checking code that if you send "ES-MX" will work. 

Reference: https://docs.microsoft.com/en-us/bingmaps/rest-services/common-parameters-and-types/supported-culture-codes

But there's actually some that aren't working like "es". The remaining thing is to document it. Will try to fork and collaborate.

Regards.
